services:
  breakingBread_db:
    image: mysql:8.0.33
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_USER_PASSWORD
    ports:
      - "$MYSQLDB_PORT_EXPOSE:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./images:/var/lib/mysql-files
    networks:
     - breakingBread

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: ./.env
    environment:
      PMA_HOST: breakingBread_db
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    ports:
      - "$PHPMYADMIN_PORT_EXPOSE:80"
    networks:
      - breakingBread

  backend:
   build: ./backend
   env_file: ./.env
   depends_on:
     - breakingBread_db
   links:
     - breakingBread_db
   ports:
   - "$BACKEND_PORT_EXPOSE:3000"  
   networks:
     - breakingBread

   
  nginx:
    image: nginx:1.19.0
    ports:
      - "$NGINX_PORT_EXPOSE:80"
    volumes:
      - ./frontend/:/usr/share/nginx/html
    depends_on:
      - backend

    
networks:
  breakingBread:
  
volumes:
  db_data: